baseline: Todo dia um novo texto, sem exceção.
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Dorly
  - Static Site Generator
  - SSG
author: Dorly
description: Escrever todos os dias é a fórmula para pensar melhor.
date:
  format: j F Y
  timezone: America/Sao_Paulo
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: Diário do Dorly
baseurl: /
canonicalurl: true
